### ISSUE TITLE
Bugfix-collection issue

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1831]
Things we should fix in a bugfix release

- [x] -  missing underscore breaking helis - merged

- [x] -  town markers not on roads - #1832 - ready for merge

- [x] -  Issue: #1808 - PR: #1809 - merged

- [x] -  Revert likely mismerge of enableDebugConsole list - #1846

- [x] -  Could throw in the ammo truck spawning. People have been complaining about it recently and it's an easy fix. - #1833 - ready for merge

- [x] -  log macros - merged

- [x] -  Fix or remove punishment missions against occupant-controlled towns. Since 2.4 they're instant-win for invaders due to lack of civilians spawning. - no PR yet

- [x] -  Logistic Nodes for 3CB Faction Smuggler Boats (If Suitable), - no PR yet

- [x] -  BAF Template go over it again and Remove Cargo Trucks with _B as these come with Containers. 😠 - PR shortly

- [x] -  Fix the town garrison spawning bug - PR: #1837 - review required

- [x] -  fix adding rebel units to unspawned garrisongs - #1835 - ready for merge

- [x] -  Disable Gunship in Modsets that are not Vanilla - Issue: #1855 PR #1856 - ready for merge

- [x]  - QRF supports incorrectly require an available airport  - Issue #1844 - no PR yet

- [x]  - Sahrani Load save Vehicle Placement  - Issue #1816 - no PR yet

- [x]  - Fixed orbital strikes deleting HQ assets - #1858 - merged

- [x]  - Fix createVehicleCrew leader selection - #1862 - merged

**Comment by Lazejun** [comment]
Something small, i doubt it happened still useful to have i guess.
Issue: #1808 
PR: https://github.com/official-antistasi-community/A3-Antistasi/pull/1809

**Comment by jaj22** [comment]
- Revert likely mismerge of enableDebugConsole list.

**Comment by jaj22** [comment]
Could throw in the ammo truck spawning. People have been complaining about it recently and it's an easy fix.

**Comment by HakonRydland** [comment]
log macros

**Comment by jaj22** [comment]
- Fix or remove punishment missions against occupant-controlled towns. Since 2.4 they're instant-win for invaders due to lack of civilians spawning.

**Comment by Lazejun** [comment]
Todo:
Logistic Nodes for 3CB Faction Smuggler Boats (If Suitable),
BAF Template go over it again and Remove Cargo Trucks with _B as these come with Containers. 😠

**Comment by Orange1861** [comment]
Fix the garrison spawning bug.
PR: #1837

**Comment by jaj22** [comment]
#1844 is pretty bad and an easy fix, so that should be in there. Should be done tonight.

**Comment by jaj22** [comment]
#1878 description.ext fixes should be in there.

**Comment by Bob-Murphy** [comment]
Shit's done
